name: Build and Release

on:
  release:
    types:
      - created

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v3
    - uses: dart-lang/setup-dart@v1
    - run: dart pub get
    - run: dart compile exe bin/server.dart -o fluffygate
    - name: Upload release binaries
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["./fluffygate"]'